core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path('welcome', views.welcome, name='welcome'),
    path('register', views.register, name='register'),
    path('terms', views.terms, name='terms'),
    path('privacy', views.privacy_policy, name='privacy'),
    path('logout', views.logout, name='logout'),
]

social_ng/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from feed import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.FeedView.get, name='home'),
    path('', include('core.urls')),
    path('', include('feed.urls')),
    path('', include('accounts.urls')),
    path('', include('moments.urls')),
]

urlpatterns = urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/welcome/content.html
{% load widget_tweaks static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>{{page_title}} / WeSocify</title>
<meta charset="UTF-8" />
<meta name="theme-color" content="#3d70b2"/>
<meta name="description" content="Welcome to Social NG. Join Social NG. Connect with your friends and family. Interact. Share ideas. Get updates all over NG." />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0,viewport-fit=cover" />
<link rel="stylesheet" href="{% static 'assets/css/uikit.css' %}" type="text/css">
<link href="{% static 'style.css' %}" type="text/css" rel="stylesheet">
<link href="{% static 'css/main.css' %}" type="text/css" rel="stylesheet">
<link href="{% static 'css/main-2.css' %}" type="text/css" rel="stylesheet">
<link href="{% static 'css/bootstrap.css' %}" type="text/css" rel="stylesheet">
<link href="{% static 'css/animate.css' %}" type="text/css" rel="stylesheet">
</head>

<body>
<div class="progress-loading" id="loading-bar"><div class="indeterminate"></div></div>
<div class="app-overlay"></div>
  
<div class="login-wrapper">
<div class="login-container row display-flex">
<div class="login-sidebar col col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12">
<div class="login-sidebar-content is-hidden-mobile">
<img src="/static/images/sidebar-phone.png" alt="sidebar-picture">
</div>
</div>

<div class="login-content col col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12">
<div id="particles-js"></div>
<div id="login-account-form">
<div class="container-fluid d-flex align-center justify-center login-form-container login-form-mobile">
<div class="form-title text-center">Welcome back, log in</div>

<form action="{% url 'core:welcome' %}" method="POST" autocomplete="off">
{% csrf_token %}
<div class="login-form">
{% if error %}
<div class="notification-box notification-box-extra notification-box-error">
<p>{{error}}</p>
<div class="notification-close notification-close-error"></div>
</div>
{% endif %}
<div class="form-group label-floating">
<label class="control-label">Phone number, username or e-mail</label>
{% render_field form.username class="form-control" type="text" maxlength="50" required="required" %}
<span class="material-input"></span>
</div>

<div class="form-group label-floating">
<label class="control-label">Password</label>
{% render_field form.password class="form-control" id="password" type="password" required="required" %}
<div id="toggle-password" class="button">
<svg class="icon icon--20" viewBox="0 0 24 24"><path d="M22 12C22 12 19 18 12 18C5 18 2 12 2 12C2 12 5 6 12 6C19 6 22 12 22 12Z"></path><circle cx="12" cy="12" r="3"></circle></svg>
</div>
<span class="material-input"></span>
</div>

<div class="is-flex justify-content-center">
<a href="/forgot">Forgot password?</a>
</div>

<button class="login-button-full" type="submit" style="font-weight:600">Sign In</button>
</form>
<a class="login-button-outline" href="{% url 'core:register' %}">Create an account</a>
</div>
</div>

</div>
</div>

</div>

<footer class="bg-white">
<div class="container-fluid" style="padding:4em 0 0 0;">
<div class="row justify-content-between" style="margin:0">
<div class="app-actions d-flex align-items-center col-sm-6 col-lg-3 mb-5 mb-lg-0 flex-column">
<h4><sup>We</sup>Socify</h4>
<p>is built for Nigerians by a Nigerian.</p>
<p>Powered and coded with <i class="fas fa-heart heart-beat" style="color: #f71416;"></i> by Chris Ade.</span> <br> Made in 🇳🇬 </p>
</div>

<div class="col-6 col-sm-6 col-md-2 col-lg-2 mb-4 mb-lg-0">
<p class="mb-4" style="font-family:BRFirma Bold;font-size:17px">Links</p>
<ul class="nav flex-column">
<li class="nav-item mb-3">
<a href="/support">Support</a>
</li>
<li class="nav-item mb-3">
<a href="{% url 'core:privacy' %}">Privacy policy</a>
</li>
<li class="nav-item mb-3">
<a href="{% url 'core:terms' %}">Terms &amp; conditions</a>
</li>
</ul>
</div>

<div class="col-6 col-sm-6 col-md-2 col-lg-2 mb-4 mb-lg-0">
<p class="mb-4" style="font-family:BRFirma Bold;font-size:17px">Reach out</p>
<ul class="nav flex-column">
<li class="nav-item mb-3">
<p class="mb-0"><a href="mailto:help@social-ng.com">help@wesocify.com</a></p>
</li>
<li class="nav-item mb-3">
<p class="mb-0">
<a href="tel:2348161201965">+234 (0) 816 120 1965</a>
</p>
</li>
</ul>
</div>

<div class="col-6 col-sm-6 col-md-3 col-lg-3 mb-4 mb-lg-0">
<p class="mb-4" style="font-family:BRFirma Bold;font-size:17px">Address</p>
<ul class="nav flex-column">
<li class="nav-item mb-3">
<span>GEM 11 Aralopon Str., Ilesa, OS, NG</span>
</li>
</ul>
</div>
</div>
</div>

<div style="border-top:1px solid rgba(225, 225, 225, .2)">
<div class="container" style="padding-bottom: .5em">
<div class="row justify-content-center" style="margin:0">
<div class="col-12">
<p class="text-center mb-0" style="font-size:14px">&copy; 2022 | WeSocify Inc.</p>
</div>
</div>
</div>
</div>
</footer>

</body>
<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'js/eruda.min.js' %}"></script>
<script src="{% static 'js/htmx.min.js' %}"></script>
<script src="{% static 'js/functions.js' %}"></script>
<script src="{% static 'plugins/particles-js/particles.min.js' %}"></script>
<script src="{% static 'js/material.min.js' %}"></script>
<script src="{% static 'assets/js/uikit.js' %}"></script>
<script>
eruda.init();
</script>
</html>

templates/welcome/register.html
{% load widget_tweaks %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>{{page_title}} / WeSocify</title>
<meta charset="UTF-8" />
<meta name="theme-color" content="#3d70b2"/>
<meta name="description" content="Welcome to Social NG. Join Social NG. Connect with your friends and family. Interact. Share ideas. Get updates all over NG." />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0,viewport-fit=cover" />
<link rel="stylesheet" href="{% static 'assets/css/uikit.css' %}" type="text/css">
<link href="{% static 'style.css' %}" type="text/css" rel="stylesheet">
<link href="{% static 'css/main.css' %}" type="text/css" rel="stylesheet">
<link href="{% static 'css/main-2.css' %}" type="text/css" rel="stylesheet">
<link href="{% static 'css/bootstrap.css' %}" type="text/css" rel="stylesheet">
<link href="{% static 'css/animate.css' %}" type="text/css" rel="stylesheet">
</head>

<body>
<div class="progress-loading" id="loading-bar">
<div class="indeterminate"></div></div>
<div class="app-overlay"></div>

<div class="login-wrapper">
<div class="login-container row display-flex">
<div class="login-sidebar col col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12">
<div class="login-sidebar-content is-hidden-mobile">
<img src="/static/images/sidebar-phone.png" alt="sidebar-picture">
</div>
</div>

<div class="login-content col col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12">
<div id="particles-js"></div>
<div id="login-account-form">
<div class="container-fluid d-flex align-center justify-center login-form-container login-form-mobile">
<div class="form-title text-center">Sign Up</div>

<div class="login-form">
<form action="{% url 'core:register' %}" method="POST" autocomplete="off">
{% csrf_token %}

{% for message in messages %}
<div class="notification-box notification-box-extra notification-box-error">
<p>{{message}}</p>
<div class="notification-close notification-close-error"></div>
</div>
{% endfor %}

<div class="form-group label-floating is-empty">
<label class="control-label">Name</label>
<input class="form-control" type="text" name="name" maxlength="50" required>
<span class="material-input"></span>
</div>

<div class="form-group label-floating is-empty">
<label class="control-label">Username</label>
<input class="form-control" type="text" name="username" required>
<span class="material-input"></span>
</div>

<div class="form-group label-floating is-empty">
<label class="control-label">Phone number or email address</label>
<input class="form-control" type="email" name="email" required>
<span class="material-input"></span>
</div>

<div class="form-group label-floating is-empty">
<label class="control-label">Date of birth</label>
<input class="form-control" type="date" name="birth_date" required>
<span class="material-input"></span>
</div>

<div class="form-group label-floating is-empty">
<label class="control-label">Password</label>
<input class="form-control" type="password" name="password" required>
<span class="material-input"></span>
</div>

<div class="form-group label-floating is-empty">
<label class="control-label">Confirm password</label>
<input class="form-control" type="password" name="cpassword" required>
<span class="material-input"></span>
</div>

<div class="is-flex justify-content-center">
<span>By registering, you agree with the <a href="{% url 'core:terms' %}" target="_blank">Terms of Use </a> and <a href="{% url 'core:privacy' %}" target="_blank">Privacy Policy</a></span>
</div>

<button type="submit" name="register" class="login-button-full">Register</button>
</form>
<a class="login-button-outline" href="{% url 'core:welcome' %}">Back to login</a>
</div>

</div>
</div>

</div>

</div>
</div>

<footer class="bg-white">
<div class="container-fluid" style="padding:4em 0 0 0;">
<div class="row justify-content-between" style="margin:0">
<div class="app-actions d-flex align-items-center col-sm-6 col-lg-3 mb-5 mb-lg-0 flex-column">
<h4><sup>We</sup>Socify</h4>
<p>is built for Nigerians by a Nigerian.</p>
<p>Powered and coded with <i class="fas fa-heart heart-beat" style="color: #f71416;"></i> by Chris Ade.</span> <br> Made in 🇳🇬 </p>
</div>

<div class="col-6 col-sm-6 col-md-2 col-lg-2 mb-4 mb-lg-0">
<p class="mb-4" style="font-family:BRFirma Bold;font-size:17px">Links</p>
<ul class="nav flex-column">
<li class="nav-item mb-3">
<a href="/support">Support</a>
</li>
<li class="nav-item mb-3">
<a href="{% url 'core:privacy' %}">Privacy policy</a>
</li>
<li class="nav-item mb-3">
<a href="{% url 'core:terms' %}">Terms &amp; conditions</a>
</li>
</ul>
</div>

<div class="col-6 col-sm-6 col-md-2 col-lg-2 mb-4 mb-lg-0">
<p class="mb-4" style="font-family:BRFirma Bold;font-size:17px">Reach out</p>
<ul class="nav flex-column">
<li class="nav-item mb-3">
<p class="mb-0"><a href="mailto:help@social-ng.com">help@wesocify.com</a></p>
</li>
<li class="nav-item mb-3">
<p class="mb-0">
<a href="tel:2348161201965">+234 (0) 816 120 1965</a>
</p>
</li>
</ul>
</div>

<div class="col-6 col-sm-6 col-md-3 col-lg-3 mb-4 mb-lg-0">
<p class="mb-4" style="font-family:BRFirma Bold;font-size:17px">Address</p>
<ul class="nav flex-column">
<li class="nav-item mb-3">
<span>GEM 11 Aralopon Str., Ilesa, OS, NG</span>
</li>
</ul>
</div>
</div>
</div>

<div style="border-top:1px solid rgba(225, 225, 225, .2)">
<div class="container" style="padding-bottom: .5em">
<div class="row justify-content-center" style="margin:0">
<div class="col-12">
<p class="text-center mb-0" style="font-size:14px">&copy; 2022 | WeSocify Inc.</p>
</div>
</div>
</div>
</div>
</footer>

</body>
<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'js/eruda.min.js' %}"></script>
<script src="{% static 'js/htmx.min.js' %}"></script>
<script src="{% static 'js/functions.js' %}"></script>
<script src="{% static 'plugins/particles-js/particles.min.js' %}"></script>
<script src="{% static 'js/material.min.js' %}"></script>
<script src="{% static 'assets/js/uikit.js' %}"></script>
<script>
eruda.init();
</script>
</html>

templates/welcome/tos.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>Terms of Service / WeSocify</title>
<meta charset="UTF-8" />
<meta name="theme-color" content="#3d70b2"/>
<meta name="description" content="Welcome to Social NG. Join Social NG. Connect with your friends and family. Interact. Share ideas. Get updates all over NG." />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0,viewport-fit=cover" />
<link href="{% static 'webfonts/BRFirma/brfirma.css' %}" type="text/css" rel="stylesheet">
<link href="{% static 'style.css' %}" type="text/css" rel="stylesheet">
<link href="{% static 'css/main.css' %}" type="text/css" rel="stylesheet">
<link href="{% static 'css/main-2.css' %}" type="text/css" rel="stylesheet">
<link href="{% static 'css/bootstrap.css' %}" type="text/css" rel="stylesheet">
<link href="{% static 'css/animate.css' %}" type="text/css" rel="stylesheet">
<link rel="stylesheet" href="{% static 'assets/css/icons.css' %}">
<link rel="stylesheet" href="{% static 'assets/css/tailwind.css' %}">

<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'js/functions.js' %}"></script>
<script src="{% static 'plugins/particles-js/particles.min.js' %}"></script>
<script src="{% static 'js/material.min.js' %}"></script>
<script src="{% static 'assets/js/tippy.all.min.js' %}"></script>  
<script src="{% static 'assets/js/uikit.js' %}"></script>
<script src="{% static 'assets/js/simplebar.js' %}"></script>
<script src="{% static 'assets/js/custom.js' %}"></script>
</head>

<body class="is-body">
<div class="progress-loading" id="loading-bar">
<div class="indeterminate"></div>
</div>
<div class="app-overlay"></div>

<main id="content" role="main" class="view-wrapper">
<div class="terms-page">

</div>
</main>

</body>
</html>