accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('<username>', views.ProfileView.get, name='profile'),
    path('<username>/feeds/', views.ProfileView.feeds, name='feeds'),
    path('<username>/with_replies/', views.ProfileView.with_replies, name='with_replies'),
    path('<username>/media/', views.ProfileView.media, name='media'),
   path('<username>/likes/', views.ProfileView.likes, name='likes'),
    path('<username>/followers/', views.followers, name='followers'),
    path('<username>/following/', views.following, name='following'),
    path('accounts/follow/<str:user>/', views.follow, name='follow'),
    path('accounts/settings/', views.settings, name='settings'),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path('welcome', views.welcome, name='welcome'),
    path('register', views.register, name='register'),
    path('terms', views.terms, name='terms'),
    path('privacy', views.privacy_policy, name='privacy'),
    path('logout', views.logout, name='logout'),
]

feed/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from feed import views

app_name = "feed"

urlpatterns = [
    path('api/feed', views.FeedListAPI.as_view()),
    path('api/feed/post', views.PostFeedAPI.as_view()),
    path('api/<username>/feed/<int:pk>', views.GetFeedAPI.as_view()),
    path('home', views.FeedView.get, name='home'),
    path('explore', views.FeedView.get, name='explore'),
    path('notifications', views.FeedView.get, name='notifications'),
    path('messages', views.FeedView.get, name='messages'),
    path('questions', views.FeedView.get, name='questions'),
    path('rooms', views.FeedView.get, name='rooms'),
    path('feed/compose/', views.FeedView.compose, name='compose'),
    path('feed/post/', views.FeedView.post, name='post'),
    path('search', views.FeedView.get, name='search'),
    path('<username>/feed/<int:pk>/', views.FeedView.view, name='view'),
    path('feed/like/<int:pk>/', views.FeedView.like, name='like'),
    path('feed/poll/vote/', views.FeedView.vote, name='vote'),
    path('feed/menu/<int:pk>/', views.FeedView.menu, name='menu'),
    path('feed/edit/', views.FeedView.update, name='edit'),
    path('feed/delete/', views.FeedView.delete, name='delete'),
    path('feed/more/', views.FeedView.more, name='more'),
    path('feed/comment/', views.CommentView.post, name='comment'),
]

social_ng/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from feed import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.FeedView.get, name='home'),
    path('', include('core.urls')),
    path('', include('feed.urls')),
    path('', include('accounts.urls')),
    path('', include('moments.urls')),
]

urlpatterns = urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from accounts.models import *
from django.contrib.auth import get_user_model
from datetime import datetime

User = get_user_model()

class Feed(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    username = models.CharField(max_length=100)
    text = models.TextField(null=True, blank=True)
    likes = models.ManyToManyField(User, blank=True, related_name="feed_likes")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('created_at',)

def get_image_filename(instance, filename):
    feed_id = instance.feed.id
    return "contents/feed/%s/%s" % (feed_id, filename)

def get_comment_image_filename(instance, filename):
    comment_id = instance.comment.id
    return "contents/comment/%s/%s" % (comment_id, filename)

class FeedPoll(models.Model):
    feed = models.ForeignKey(Feed, default=None, related_name="feed_poll", on_delete=models.CASCADE)
    choice_1 = models.CharField(max_length=25)
    choice_2 = models.CharField(max_length=25)
    choice_3 = models.CharField(max_length=25, null=True)
    choice_4 = models.CharField(max_length=25, null=True)
    votes = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

class FeedPollVotes(models.Model):
    poll = models.ForeignKey(FeedPoll, default=None, related_name="feed_poll_votes", on_delete=models.CASCADE)
    voted_by = models.ForeignKey(User, null=False, blank=False, default=None, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

class FeedImages(models.Model):
    feed = models.ForeignKey(Feed, default=None, related_name="images", on_delete=models.CASCADE)
    image = models.ImageField(upload_to=get_image_filename, verbose_name='feed_images', null=True, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)

class FeedComments(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    feed = models.ForeignKey(Feed, default=None, related_name="comments", on_delete=models.CASCADE)
    username = models.CharField(max_length=100)
    text = models.TextField(null=True, blank=True)
    likes = models.ManyToManyField(User, blank=True, related_name="comment_likes")
    created_at = models.DateTimeField(auto_now_add=True)

class FeedCommentImages(models.Model):
    comment = models.ForeignKey(FeedComments, default=None, related_name="comment_image", on_delete=models.CASCADE)
    feed = models.ForeignKey(Feed, default=None, related_name="comment_image", on_delete=models.CASCADE)
    image = models.ImageField(upload_to=get_comment_image_filename, verbose_name='comment_images', null=True, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)

feed/forms.py
from django import forms
from .models import *
from django.core.exceptions import ValidationError

class postForm(forms.ModelForm):
	""" 
	Creates a form for creating a new post
	"""
	text = forms.CharField(max_length=500, widget=forms.Textarea)
	
	class Meta:
		model = Feed
		fields = ('text',)
		
class pollForm(forms.ModelForm):
  choice_1 = forms.CharField(max_length=25, required=False)
  choice_2 = forms.CharField(max_length=25, required=False)
  choice_3 = forms.CharField(max_length=25, required=False)
  choice_4 = forms.CharField(max_length=25, required=False)
  #poll_days = forms.ChoiceField()
  #poll_hours = forms.ChoiceField()
  #poll_minutes = forms.ChoiceField()
  
  class Meta:
    model = FeedPoll
    fields = ('choice_1', 'choice_2', 'choice_3', 'choice_4',)

class post_image_form(forms.ModelForm):
	""" 
	Creates a form for uploading an image for a post
	"""
	image = forms.ImageField(required=False, label='Image')
	class Meta:
		model = FeedImages
		fields = ('image',)

feed/views.py
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.contrib import messages
from django.conf import settings
from django.http import HttpResponse, JsonResponse, Http404
from django.contrib.auth.decorators import login_required
from accounts.models import *
from moments.models import *
from .models import *
from .forms import *
from .utils import *
from .serializers import *
from rest_framework import generics
from itertools import chain

class FeedListAPI(generics.ListAPIView):
    """ 
    API endpoint for fetching all user feeds
    """
    queryset = Feed.objects.order_by('-id')
    serializer_class = UserFeedSerializer

class GetFeedAPI(generics.RetrieveAPIView):
    """ 
    API endpoint for retreiving feed by ID
    """
    queryset = Feed.objects.all()
    serializer_class = UserFeedSerializer
    
class PostFeedAPI(generics.CreateAPIView):
    """ 
    API endpoint for posting a feed
    """
    queryset = Feed.objects.all()
    serializer_class = UserFeedSerializer

class FeedView():
    @login_required
    def compose(request):
      hours = [*range(0, 24)]
      minutes =[*range(0, 60)]
      context = {
      'page_title': "Compose Feed",
      'post_form': postForm(),
      'poll_form': pollForm(),
      'poll_hours': hours,
      'poll_minutes': minutes,
      }
      return render(request, 'feed/compose/content.html', context)
      
    @login_required
    def view(request, username, pk):
        try:
            feed_object = Feed.objects.get(id=pk, user__username=username)
            user_object = request.user
            followers = get_user_followers(feed_object.user)
            context = {
            'page_title': "Feed",
            'user_profile': user_object,
            'post': feed_object,
            'followers': followers
            }
            return render(request, 'feed/view.html', context)
        except Feed.DoesNotExist:
            return render(request, 'errors/404.html')
            
    @login_required
    def get(request):
        try:
            feed_object = get_user_feed(request)
            feed = pagination(request, feed_object)
            user_following = get_user_following(request.user)
            follow_comment = get_following_comment(user_following)
            user_object = request.user
            context = {
            'page_title': "Home",
            'post_form': postForm(),
            'user_profile': user_object,
            'following': user_following,
            'posts': feed,
            'follow_comment': follow_comment,
            }
        
            return render(request, 'feed/content.html', context)
        
        except Feed.DoesNotExist:
            return render(request, 'feed/content.html', context)

    @login_required
    def suggestions(request):
        try:
            obj = get_user_suggestions(request)
            context = {
            'suggestions': obj[:4]
            }
            return render(request, 'feed/suggestions.html', context)
            
        except Exception as e:
            return render(request, 'feed/suggestions.html', context)

    @login_required
    def vote(request):
      if request.method == 'POST':
        choice = request.POST.get('choice', None)
        feed = request.POST.get('feed', None)
        poll = request.POST.get('poll', None)
        print(choice, feed, poll)

    @login_required
    def post(request):
        if request.method == 'POST':
            form = postForm(request.POST or None, request.FILES or None)
            poll = pollForm(request.POST or None)
            images = request.FILES.getlist('image')
            action = request.POST.get('action', 0)

            if form.is_valid():
                username = request.user.username
                user_id = request.user.id
                text = form.cleaned_data['text']
                feed = Feed.objects.create(user_id=user_id, username=username, text=text)
                if poll.is_valid():
                  choice_1 = poll.cleaned_data['choice_1']
                  choice_2 = poll.cleaned_data['choice_2']
                  choice_3 = poll.cleaned_data['choice_3']
                  choice_4 = poll.cleaned_data['choice_4']
                  #days = poll.cleaned_data['poll_days']
                  #hours = poll.cleaned_data['poll_hours']
                  #minutes = poll.cleaned_data['poll_minutes']
                  feed_poll = FeedPoll.objects.create(feed=feed, choice_1=choice_1, choice_2=choice_2, choice_3=choice_3, choice_4=choice_4)
                  feed_poll.save()
                for image in images:
                  feed_images = FeedImages.objects.create(feed=feed, image=image)
                  feed_images.save()
                feed.save()
                data = {
                    'post': feed,
                }
                if int(action) == 1:
                  return JsonResponse({'status': 200, 'message': 'Your feed has been posted.'})
                else:
                  return render(request, 'feed/partials/feed.html', data)
            else:
                return JsonResponse({'status': 403, 'message': 'Invalid form'}, status=403)
        else:
            return JsonResponse({'status': 403, 'message': 'Not Allowed'}, status=403)

    @login_required
    def update(request):
        if request.method == 'POST':
            content = request.POST['content']
            feed_id = request.POST['id']
            instance = Feed.objects.filter(id=feed_id).update(text=content.strip())
            if instance == 1:
                feed_object = Feed.objects.get(id=feed_id)
                page = render_to_string('feed/partials/feed.html', {'post': feed_object})
                return JsonResponse({'scode': 200, 'feed': page})
            return JsonResponse({'scode': 403}, status=403)

    @login_required
    def delete(request):
        if request.method == "POST":
            feed_id = request.POST['id']
            feed_object = Feed.objects.filter(id=feed_id)

            if Feed.objects.filter(id=feed_id).exists():
                feed_object.delete()
                return JsonResponse({'scode': 200})
            return JsonResponse({'scode': 422})
        return JsonResponse({'scode': 404})

    @login_required
    def like(request, pk):
        if request.method == "POST":
            feed_type = request.POST.get('type', 0)
            username = request.user.username
            user_id = request.user.id
            post_id = pk
            instance = Feed.objects.get(id=pk)
            if not instance.likes.filter(id=user_id).exists():
                instance.likes.add(request.user)
                instance.save()
                if int(feed_type) == 1:
                   return render(request, 'profile/partials/feed.html', context={'post': instance})
                return render(request, 'feed/partials/feed.html', context={'post': instance})
            else:
                instance.likes.remove(request.user)
                instance.save()
                if int(feed_type) == 1:
                   return render(request, 'profile/partials/feed.html', context={'post': instance})
                return render(request, 'feed/partials/feed.html', context={'post': instance})
        else:
            return redirect(reverse('home'))

    @login_required
    def share(request):
        pass
    
    @login_required
    def menu(request, pk):
        try:
            feed_object = Feed.objects.get(id=pk)
            user_followers = get_user_followers(feed_object.user)
            return render(request, 'feed/modals/view/menu.html', {'post': feed_object, 'followers': user_followers})
        except Feed.DoesNotExist:
            return JsonResponse({'scode': 404}, status=404)

    @login_required
    def more(request):
        feed_output = []
        lid = []
        if request.method == "POST":
            counter = request.POST['page']
            counter = int(counter)
            if not counter:
                return render(request, 'feed/partials/no-more-data.html')
            else:
                feed_object = Feed.objects.filter(username=request.user.username, user_id=request.user.id).order_by('-id')
                feed = pagination(request, feed_object)
                for f in feed:
                    lid.append(f.id)
        else:
            return None
        feed_output.append(feed_object)
        feed_list = list(chain(*feed_output))
        
        lid = lid[-1:]
        if len(lid) == 1:
            last_id = lid[0]
        else:
            last_id = ""

        context = {
            'posts': feed_list,
            'lid': last_id,
        }

        return render(request, 'feed/partials/filter.html', context)

class CommentView():
    @login_required
    def get(request, feed_id):
        post_object = Feed.objects.get(id=feed_id)
        comment_object = FeedComments.objects.filter(feed__id=feed_id)
        if comment_object.exists():
            page = render_to_string('feed/partials/comment.html', {'post': post_object, 'comment': comment_object})
            return JsonResponse({'scode': 200, 'comment': page})
        return JsonResponse({'scode': 403})

    @login_required
    def post(request):
        if request.method == 'POST':
            if (request.POST or None) or (request.FILES or None):
                images = request.FILES.getlist('comment-image')
                username = request.user.username
                user_id = request.user.id
                feed_id = request.POST['target']
                text = request.POST['comment']
                post_object = Feed.objects.get(id=feed_id)
                comment_obj = FeedComments.objects.create(user_id=user_id, username=username, text=text, feed_id=feed_id)
                comment_obj.save()
                for img in images:

templates/feed/view/content.html
{% load humanize static custom_date %}
<div class="ui-block post ui-no-radius ui-margin-t30" id="feed{{post.id}}">
<div class="flex items-center px-3 pt-5 pb-2">
<div class="flex flex-1 space-x-4">
<a href="{% url 'accounts:profile' username=post.user.username %}" class="rounded-full"><img src="{{post.user.avatar.url}}" class="bg-gray-200 border border-white rounded-full w-12 h-12"></a>
<div class="block">
<div>
<span class="font-bold">{{post.user.name}} </span> • <span>{{post.created_at|custom_date}}</span>
</div>
<a href="{% url 'accounts:profile' username=post.user.username %}" class="ui-at">@{{post.user.username}}</a>
</div>
</div>

</div>

<div class="py-2 px-4 space-y-3" id="feed-text{{post.id}}">{{post.text|linebreaksbr|safe}}</div>

{% if post.images.all %}
<div class="px-4">
{% if post.images.all.count == 1 %}
<div class="feed-image" uk-lightbox>
{% for image in post.images.all %}
<a class="feed-image-item" href="{{image.image.url}}" style="background-image: url({{image.image.url}});display: block;" title="{{post.username}}'s post"></a>
{% endfor %}
</div>
{% elif post.images.all.count == 2 %}
<div class="feed-image" uk-lightbox>
<div class="feed-image-column">
{% for image in post.images.all %}
<a class="feed-image-item image-item" href="{{image.image.url}}" style="background-image: url({{image.image.url}});" title="{{post.username}}'s post"></a>
{% endfor %}
</div>
</div>
{% elif post.images.all.count == 3 %}
<div class="feed-masonry-grid" uk-lightbox>
{% for image in post.images.all %}
{% if forloop.counter == 1 %}
<div class="feed-masonry-column">
<a href="{{post.user.avatar.url}}" style="background-image: url({{post.user.avatar.url}});" title="{{post.username}}'s post"></a>
</div>
{% endif %}
{% endfor %}
<div class="feed-masonry-columns">
{% for image in post.images.all %}
{% if forloop.counter > 1 %}
<a href="{{image.image.url}}" style="background-image: url({{image.image.url}});" title="{{post.username}}'s post"></a>
{% endif %}
{% endfor %}
</div>
</div>
{% elif post.images.all.count == 4 or post.images.all.count > 4 %}
<div class="feed-masonry-grid" uk-lightbox>
{% for image in post.images.all %}
{% if forloop.counter == 1 %}
<div class="feed-masonry-column">
<a href="{{post.user.avatar.url}}" style="background-image: url({{post.user.avatar.url}});" title="{{post.username}}'s post"></a>
</div>
{% endif %}
{% endfor %}
<div class="feed-masonry-columns">
{% for image in post.images.all %}
{% if forloop.counter > 3 %}
<a href="{{image.image.url}}" class="is-hidden"></a>
{% else %}
{% if forloop.counter == 3 %}
<a href="{{image.image.url}}" style="background-image: url({{image.image.url}});" title="{{post.username}}'s post">
{% with total=post.images.all.count %}
{% if total > 3 %}
<span class="bg-gray-900 bg-opacity-30">
+{{total|add:-3}} more
</span>
{% endif %}
{% endwith %}
</a>
{% else %}
<a href="{{image.image.url}}" style="background-image: url({{image.image.url}});" title="{{post.user.username}}'s post"></a>
{% endif %}
{% endif %}
{% endfor %}
</div>
</div>
{% endif %}
</div>
{% endif %}

<div class="px-4 space-y-3">
<div class="ui-feed-footer pt-2 space-y-3"> 
<div class="ui-feed-footer-inner">
<div class="social-count view-count">
<div class="comments-count">
<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-message-circle"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path></svg>
{% if post.comments.all.count >= 1 %}
<span>{{post.comments.count|intword}} </span>
{% endif %}
</div>

<div class="shares-count">
<svg role="img" class="icon" width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
<desc id="swapVerticalIconDesc"></desc>
<path d="M4 8L7 5L10 8"></path>
<path d="M7 20L7 6"></path>
<path d="M20 17L17 20L14 17"></path>
<path d="M17 5L17 19"></path>
</svg>
{% if post.likes.all.count >= 1 %}
<span>{{post.likes.count|intword}} </span>
{% endif %}
</div>

<div class="likes-count {% if request.user in post.likes.all %} is-liked {% endif %}" hx-post="{% url 'feed:like' pk=post.id %}" hx-target="#feed{{post.id}}" hx-swap="outerHTML" data-id="{{post.id}}">
<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-heart"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path></svg>
{% if post.likes.all.count >= 1 %}
<span>{{post.likes.count|intword}} </span>
{% endif %}
</div>

<div class="likes-count">
<svg role="img" xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" aria-labelledby="shareAndroidIconTitle">
<title id="shareAndroidIconTitle">Share</title>
<path d="M16 8L8 11 16 8zM16 16L8 13 16 16z"></path>
<circle cx="6" cy="12" r="2"></circle>
<circle cx="18" cy="7" r="2"></circle>
<circle cx="18" cy="17" r="2"></circle>
</svg>
</div>

</div>
<hr>
</div>
</div>

<div class="ui-comment-list border-t w-full pt-4 space-y-4" id="comments{{post.id}}" style="height:100%;max-height:100%;min-height:100%;">
{% include 'feed/comments.html' %}
</div>

</div>
</div>

{% include '../modals/view/menu.html' %}

templates/feed/view/footer.html
<div class="ui-add-comment">
<form method="POST" enctype="multipart/form-data" action="{% url 'feed:comment' %}" class="comment_form" data-id="{{post.id}}">
{% csrf_token %}
<input type="hidden" name="target" value="{{post.id}}">
<input class="hidden" type="file" name="comment-image" id="comment-image{{post.id}}">
<div class="comment-field" style="background-color: #fff;">
<div class="w-full">
<input type="text" name="comment" placeholder="Post your reply" class="p-3 w-full" required>
</div>
<div class="flex ml-auto h-full items-center">
<div class="ui-comment-action-buttons">
<a class="ui-comment-action-button">
<svg class="icon" role="img" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" aria-labelledby="happyFaceIconTitle"><path d="M7.3010863,14.0011479 C8.0734404,15.7578367 9.98813711,17 11.9995889,17 C14.0024928,17 15.913479,15.7546194 16.6925307,14.0055328"></path>
<line stroke-linecap="round" x1="9" y1="9" x2="9" y2="9"></line>
<line stroke-linecap="round" x1="15" y1="9" x2="15" y2="9"></line>
<circle cx="12" cy="12" r="10"></circle>
</svg>
</a>
<a class="ui-comment-action-button" onclick="$('#comment-image{{post.id}}').trigger('click');">
<svg role="img" class="icon" width="17" height="17" viewBox="0 0 24 24"><rect width="18" height="18" x="3" y="3"></rect><path stroke-linecap="round" d="M3 14l4-4 11 11"></path><circle cx="13.5" cy="7.5" r="2.5"></circle><path stroke-linecap="round" d="M13.5 16.5L21 9"></path></svg>
</a>
<button class="ui-comment-action-button ui-send-button" type="submit">
<svg role="img" viewBox="0 0 18 25" aria-labelledby="sendIconTitle" class="icon icon-send"><polygon points="21.368 12.001 3 21.609 3 14 11 12 3 9.794 3 2.394"></polygon></svg>
</button>
</div>
</div>
</div>
</form>
</div>

templates/feed/view/header.html
<div class="ui-feed-header">
<a href="{% url 'feed:home' %}" class="ui-feed-header-button hover:bg-gray-200 rounded-full p-2 transition -mr-1">
<svg class="icon icon--20" role="img" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M9 6l-6 6 6 6"></path><path d="M21 12H4"></path><path stroke-linecap="round" d="M3 12h1"></path></svg>
</a>
<div class="ui-feed-header-title">Feed</div>
<div class="modal-trigger ui-feed-header-menu" data-modal="feed-menu-modal" data-id="{{post.id}}"><i class="icon-feather-more-horizontal text-2xl hover:bg-gray-200 rounded-full p-2 transition -mr-1"></i></div>
</div>